# Configuración de Build para Netlify
[build]
  # Directorio base donde se encuentra el proyecto React
  base = "antologia-react"
  # Comando para construir el proyecto Vite
  command = "npm run build"
  # Directorio donde se guardan los archivos finales
  publish = "dist"

# Regla de redirección para Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200