// src/components/poems.js

export const poemsData = {
  'intro': {
    title: 'Introducción',
    content: [
      'Si escribo lo que siento es porque así disminuyo la fiebre de sentir.',
      'Lo que confieso no tiene importancia, pues nada tiene importancia.',
      'Hago paisajes con lo que siento.',
      'Hago fiestas de las sensaciones.',
      '(libro del desasosiego- Fernando Pessoa)'
    ]
  },
  'poema-1': {
    title: 'Conejo Blanco',
    content: [
      'Llegas tarde como de costumbre -me dijo-…',
      '',
      'La noche anterior había llamado pero no fue muy prudente hablar en ese momento,',
      'esta mañana el teléfono sonó para despertarme,',
      'habíamos tenido pesadillas en lo que va corrido de las últimas noches',
      'y esta era una de las razones para llegar a su habitación',
      'y contemplar el conejo blanco que por fin había enjaulado,',
      'cosa que me aterro profundamente,',
      'y que para ella se convertía en una sonrisa pícara dibujada en su rostro.',
      '',
      'Yo preferí omitir el descaro para recostarme con la mirada perdida en el techo,',
      'hasta que sus ojos inquietantes por fin me cuestionaron acerca de mis pensamientos.',
      'Esto siempre me detenía en un rápido análisis sobre lo que ella debería saber',
      'y lo que yo debería omitir y olvidar para mi salud mental…',
      '',
      'Deshice pequeñas cadenas y ataduras en mi lengua,',
      'contraje el espacio entre nuestras miradas mientras sentía el temblor en todo mi cuerpo',
      'y sentí de nuevo su caricia angelical,',
      'aquellas que tantas veces he buscado en otras manos tan torpes y de buenas intenciones',
      'que a duras penas si llego a entender que es una caricia.',
      '',
      'Ella no, ella lo hace con el alma y sabe llegar hasta la mía y como diría Oliverio Gironda,',
      'después de conocer una mujer etérea,',
      '¿puede brindarnos alguna clase de atractivos una mujer terrestre?'
    ]
  },
  'poema-2': {
    title: 'Sed de ti',
    content: [
      'Porque tengo sed de ti y de tu cuerpo cálido,',
      'tengo sed de tus labios y tus senos,',
      'tengo sed de tu mirada y tu respiración,',
      'de esas noches que no han llegado y que no sé si llegarán.',
      '',
      'Tengo sed de nuestros silencios abrazados,',
      'de nuestras caricias interminables y de esos besos profundos por todo el cuerpo,',
      'de esas tardes mirando puestas de sol,',
      'de esos días de lluvia caminando tomados de la mano,',
      'de esos momentos sin hacer nada o simplemente comiendo helado,',
      'viendo una película y en algunas ocasiones no verla.',
      '',
      'Tengo sed de reírnos por bobadas y de nuestros juegos tontos que solo nosotros entendemos,',
      'tengo sed de todos esos momentos,',
      'tengo sed de tus tristezas, de tus alegrías, de tus alas, de tu calor,',
      'tengo sed de tu cuerpo ansioso,',
      'tengo sed de ti… Mujer de mi media noche.'
    ]
  },
  // Puedes añadir el resto de los poemas aquí...
  'poema-3': {
    title: 'Aquí me tienes',
    content: [
      'Aquí me tienes,',
      'buscando palabras para ti,',
      'letras profanas que persigo incansablemente',
      'en el rincón de mi memoria,',
      'en libros leídos',
      'y sentimientos perdidos.',
      '',
      'Un mundo quisiera crear,',
      'uno solo para los dos',
      'y para nadie más.',
      '',
      'Trato de entender lo que pienso',
      'y lo que siento,',
      'pero no hallo respuesta.',
      '',
      'Me canso de ser lo que soy,',
      'quiero dar,',
      'y no recibo nada.',
      '',
      'Me canso de mí mismo,',
      'de esta sed que no calma',
      'ninguna bebida.',
      '',
      'Quisiera beber la miel de tus labios,',
      'el néctar dulce de tu piel.',
      '',
      'Pero no…',
      'aquí me encuentro otra vez,',
      'en medio de la noche,',
      'queriendo estar contigo,',
      'y aún sigo solo.',
      '',
      'Porque el quererte y desearte tanto',
      'es insuficiente.',
      'No basta con pasarme la vida',
      'pensando en ti,',
      '',
      'no es suficiente mi tristeza,',
      'mi melancolía de no tenerte,',
      'ni es suficiente desgarrar mi alma',
      'y plasmarla en papel.',
      '',
      'Este sentimiento indescifrable,',
      'imposible de escribir,',
      'cuyas palabras aún no existen,',
      'pertenece a lo más recóndito del corazón,',
      'a lo inalcanzable.',
      '',
      'A veces siento miedo',
      'de esto que soy,',
      'miedo de mí mismo,',
      'de que tal vez pertenezca',
      'a otro lugar,',
      'a una vida que no fue la mía.',
      '',
      'Y de qué me sirve escribirte',
      'si no consigo tu corazón,',
      'si no extingo estos sentimientos',
      'indescifrables,',
      'intensos',
      'y, al parecer…',
      '',
      'eternos.'
    ]
  },
  'poema-4': {
    title: 'Los Diminutos (Versión poética)',
    content: [
      'En las esquinas de la casa',
      'viven seres diminutos,',
      'nacidos en nidos olvidados de arañas,',
      'donde flotan hilos oscuros por el polvo,',
      'como sueños nebulosos.',
      '',
      'Son apenas un soplo,',
      'un centímetro de ingenio,',
      'ladrones de migas de pan',
      'y de granos de azúcar.',
      '',
      'Han visto tormentas de amor',
      'hundiendo barcos de papel,',
      'con timones de chinchetas',
      'y remos de fósforos apagados.',
      '',
      'Me han visto llorar,',
      'te han visto llorar,',
      'y han escuchado el silencio',
      'cuando pesaba más que la palabra.',
      '',
      'Ellos saben de mí',
      'más que yo mismo,',
      'me observan como te observaban a ti,',
      'y aún así se sorprenden',
      'de cuánto he vuelto a sonreír,',
      'de cuánto los amo,',
      'y de cuánto agradezco',
      'que existan aquí,',
      'en nuestra habitación,',
      'recordándome el amor que ya no está.'
    ]
  },
  'poema-5': {
    title: 'Los Diminutos (Versión fantasía)',
    content: [
      'En mi casa habitan unos seres muy pequeños,',
      'tan pequeños que no miden más de un centímetro.',
      'Los descubrí una noche en los nidos abandonados de arañas,',
      'esos rincones donde flotan hilos,',
      'algunos aún algodonosos y tibios,',
      'otros ya oscuros y polvorientos,',
      'como la nostalgia de lo que fue hogar.',
      '',
      'Son seres ingeniosos:',
      'construyen barcos de papel para navegar',
      'las tormentas de amor y de tristeza que cruzan por la habitación.',
      'Colocan una chincheta como timón,',
      'y utilizan fósforos sin encender como remos.',
      '',
      'Desde su escondite observan todo.',
      'Me han visto llorar,',
      'te han visto llorar,',
      'y han escuchado el silencio más hondo',
      'cuando la casa parecía naufragar.',
      '',
      'Conocen mis secretos,',
      'mi intimidad más que yo mismo.',
      'Han sido testigos de ese amor que compartimos,',
      'de ese hogar y de esa mujer',
      'que ya no habita en mi vida.',
      '',
      'Pero también se han sorprendido',
      'de lo mucho que he vuelto a sonreír.',
      'Y aunque nunca han hablado,',
      'sé que me acompañan.',
      'Y yo los amo,',
      'porque habitan en nuestra antigua habitación',
      'y en la memoria viva de lo que fuimos.'
    ]
  },
  'bio': {
    title: 'Autobiografía',
    content: [
      'Aquí aparecerá la autobiografía del autor.'
    ]
  },
  'apoyo': {
    title: 'Apoya al autor',
    content: [
      'Si te gusta el contenido que creo, puedes mostrar tu apoyo a través de una pequeña contribución económica.',
      'Tu ayuda me permite seguir escribiendo, explorando nuevas ideas y compartiendo mi arte contigo.'
    ],
    specialContent: 'donationButtons' // Indicador para contenido especial
  },
  'escribeme': {
    title: 'Escríbeme',
    content: [
      '¿Tienes alguna pregunta, un comentario o simplemente quieres saludar? Me encantaría saber de ti.'
    ],
    specialContent: 'contactButtons' // Indicador para los botones de contacto
  }
};

export const poems = Object.entries(poemsData).map(([id, data]) => ({ id, ...data }));